### ISSUE TITLE
(55) Ingest Aerial Photos Collection

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#418]
### Descriptive Summary

Collection of complex image objects.  Each complex object is a flight, which consists of a collection record, index(es), and sheets.  The collection is represented on 21 sheets in the Aerials folder on dams_ingest.

### Background 

This is a legacy collection that was up in CONTENTdm and is currently offline.

### Acceptance Criteria

This is what done looks like:

* [x] Metadata ingest spreadsheet has been finalized per Bulkrax metadata specification
* [x] Collection has been successfully ingested
* [ ] Images display properly
* [x] Metadata displays properly
* [x] Collection has been published and is available to users on DAMS homepage

### Related Work
Before the collection is ingested in production the following tickets will need to be resolved:

- [x] [Controlled terms with hyphens in the labels not displaying in full#561](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/561)
- [x] [Aerials metadata: Backslashes appearing in front of semi-colons#567](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/567)
- [x] [Update Geonames URIs for counties to local terms#568](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/568)

**Comment by rmjaffe** [comment]
The bug identified in #445 needs to be resolved before the Q1 aerials are ingested.

**Comment by rmjaffe** [comment]
This ticket is now blocked by the need to complete #508.

**Comment by rmjaffe** [comment]
@rschwab @snehagunduraoUL Another question:  Sue provided me with a representative image for the aerials collection (I have both a jpg and a tiff version).  What is the best way to get that up in the DAMS?  Can I add it as a file on the collection metadata row of the ingest spreadsheet?

**Comment by snehagunduraoUL** [comment]
@rmjaffe I just tried this with the dashboard UI and the collection representative images only support JPG, GIF or PNG as per the screenshot below. And the best way would be to just upload it manually if it is just one image.
<img width="1014" alt="Screen Shot 2022-11-29 at 4 20 00 PM" src="https://user-images.githubusercontent.com/92340457/204677127-b6536b3c-8a1e-425a-b301-672e9ea59601.png">

**Comment by rschwab** [comment]
It's hyrax, so what seems like would be the right way is never the right way...

The branding image above is for the banner on a collection landing page, not the representative image:
![Firefox_Screenshot_2022-11-30T17-50-28 846Z](https://user-images.githubusercontent.com/515412/204872233-7588e400-8c2e-4187-a9fe-24215ef18627.png)

The representative image can be added by editing the collection and adding a work ID into the thumbnail field:
![Firefox_Screenshot_2022-11-30T17-49-35 218Z](https://user-images.githubusercontent.com/515412/204872323-d4020018-9f8a-4b95-89a0-5fc07673d635.png)

So the way to do this is include the representative image as a work on an ingest spreadsheet. It can be marked private to keep it from being a work in the collection on the public view, if desired. Then after the ingest is completed find the work ID that was generated for the representative image, and edit the collection and enter that ID into the thumbnail field.

**Comment by rmjaffe** [comment]
@rschwab Egads...can't say that I'm shocked.  I have a similar question about supplying the link behind the 'Visit the collection guide' link in the About the collection section.  The link to the aerials libguide is on the relatedResource property in the collection metadata on the ingest sheets, but I'm guessing it would also need to be added manually via the editor in the UI?

**Comment by rschwab** [comment]
That link is generated from relatedResource, so having it on the ingest sheet should work by itself.

**Comment by rmjaffe** [comment]
Surprise plot twist.

**Comment by chesleyperry** [comment]
The representative image is from the 1948 flight.  We could wait until the 1948 collection is ingested, and then edit the collection with the ID of that specific photo.  I should be able to find it again pretty easily.

**Comment by rmjaffe** [comment]
Blocked by #538; worst can fill down controlled values on ingest spreadsheets.

**Comment by rmjaffe** [comment]
Just had a look at the first flight in production and it seems that the thumbnail images aren’t displaying correctly on the collection landing page or on the parent work display page.  They do load in the UV on the child work pages.

![Image](https://user-images.githubusercontent.com/32003407/225684556-e6394b36-b2be-4781-96ca-f6f20283410d.png)

![Image](https://user-images.githubusercontent.com/32003407/225684566-7de53d74-3bb6-4053-a10a-b86109a0cf86.png)

**Comment by chesleyperry** [comment]
The representative image for the collections is 05_05_48_CDF5_2_86.tif.  
@rmjaffe If I'm reading the history of this issue correctly, we should wait until the image is loaded on an ingest, then specify the work ID in the thumbnail field for the collection.  It looks like the 1948 flight will be loaded in the 6th aerials spreadsheet.  Is that correct?

**Comment by rmjaffe** [comment]
Yes, this was my understanding as well -- just wanting to be sure that filename is documented somewhere that's easy to find.  Thanks!

**Comment by chesleyperry** [comment]
Issue: Collection guide link on collection landing page is broken.  Should go to: https://guides.library.ucsc.edu/maps/aerial but it goes to https://digitalcollections.library.ucsc.edu/collections/Aerial%20photo%20guide:%20https://guides.library.ucsc.edu/maps/aerial

**Comment by rmjaffe** [comment]
Issue:  Here's another example (in addition to 1928-A) where the thumbnail image used for the flight is not the same as the image belonging to the first child work:

![Image](https://user-images.githubusercontent.com/32003407/229925680-96a8c71f-a8c2-40ba-94f1-8d6a6e327d02.png)

The thumbnail image for the 1949 San Benito flight should be image belonging to the first child work, 1949_bux_index_geo_key.tif.

**Comment by chesleyperry** [comment]
QA spreadsheet for the production ingests: https://docs.google.com/spreadsheets/d/1qpztAQ8hWkOajRGwKeNgFor3eDwMDiWW2gMNgfXKNmo/edit#gid=0

**Comment by snehagunduraoUL** [comment]
@rmjaffe @chesleyperry I think I know why the representative thumbnail has the incorrect image. For 1928-A, it was because the thumbnails were not available because of the height/width issue when we ingested the work. For 1949 San Benito...there was date error([1949]) for that particular work. 
Solr re-index should fix this issue. Currently Aerials_7 is under progress. I will do a re-index once Aerials_7 is completed.

**Comment by afrebert** [comment]
Aerial 12 ingest: Error on sidekiq for 1965d_sc_1-152.tif and 1965d_sc_1-158.tif:
The corrupt files have been replaced with new scans

**Comment by rmjaffe** [comment]
@snehagunduraoUL & @afrebert :  I'm feeling like we should wait to reload/re-ingest aerials_12 until after we've loaded the rest of the collection.  Is that OK or is more satisfaction to be gained in resolving the image issue first?

**Comment by afrebert** [comment]
@snehagunduraoUL & @afrebert : We can wait re-ingesting 12. I'm pretty confident that the image issue is resolved, we don't have to confirm immediately.

**Comment by snehagunduraoUL** [comment]
@rmjaffe For this issue...just a sidekiq process should be re-run. I did that just now and the images display correctly.
https://digitalcollections.library.ucsc.edu/concern/works/bk128g58k?locale=en

**Comment by rmjaffe** [comment]
@snehagunduraoUL The thumbnail on 1969-G needs to be updated to show the first child work.

**Comment by rmjaffe** [comment]
Actually, this thumbnail issue appears to be affecting a handful of flights.  Should I create a bug ticket for this?
