### ISSUE TITLE
(5) Recreate DAMS project and roadmap boards

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#422]
### Descriptive Summary

In advance of reconvening as a non-assessment project team, we've decided that we'd like to refresh our boards and relocate them to the [ucsc-library-digital-collections](https://github.com/UCSCLibrary/ucsc-library-digital-collections) repo.

The existing boards will be closed out.

### Acceptance Criteria

This is what done looks like:

* [x] New project board created using Projects (beta)
* [x] Relevant work tickets transferred to new project board
* [x] New roadmap board created using Projects (beta)
* [x] Epics updated on old roadmap board
* [x] Relevant epic tickets transferred to new project board
* [x] Recreate issue templates
* [x] Communication to DAMS stakeholders
* [x] Close old project and roadmap boards

### Related Work 

This work will require a brief pause on actively using (moving tickets, making changes, adding issues, etc.) the project and roadmap boards.
