### ISSUE TITLE
View All Collections (aka A-Z) page

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#424]
### Descriptive Summary

This epic pulls together issues relating to the [View All Collections](https://digitalcollections.library.ucsc.edu/collections) page.  Issues include bug tickets as well as desired enhancements.

### Background

Work that has already been done to create the page and the A-Z list of collections is represented on the legacy DAMS project board, including:

- UCSCLibrary/dams_project_mgmt#247 Mock Up for new A-Z list of collections
- UCSCLibrary/dams_project_mgmt#277 Create new A-Z list of collections page (desktop)

### Acceptance Criteria

This is what done looks like:

**Bugs**
- [x] Make the thumbnail size uniform in the A-Z list[#420](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/420)
- [x] Pagination on A-Z page/About Our Collections in DAMS-staging[#382](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/382)

**Enhancements**
- [x] Update language in About our Collections box on A-Z pages[#381](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/381)
- [x] Create new A-Z List of Collections page: Mobile[#375](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/375)
- [x] Sorting and faceting of collections on A-Z page[#376](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/376)
