### ISSUE TITLE
Complex Objects

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#425]
### Descriptive Summary

This epic pulls together issues relating to the interim/tier one display of complex image objects.  Issues include bug tickets as well as desired enhancements.

Implementation of the interim strategy will likely be concurrent with the removal and reingest of MS 20: MS 20: Removal and reingest of full collection[#370](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/370)

### Background

Work that has already been done in support of complex image objects is represented on the legacy DAMS project board.

### Acceptance Criteria

This is what done looks like:

**Enhancements**
First action is to finalize the selection of an approach:

Approach 1: Detail and create mock-ups for interim/tier one complex image objects display (option #1)[#395](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/395)
Approach 2: Update display settings to show child vs. parent metadata record on work display page (interim/tier one option #2)[#412](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/412)

- [ ] Implement new search & retrieval experience for complex objects[#398](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/398)

**Bugs**
- [ ] Master filename not automatically displaying in CMF metadata records[#410](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/410)
- [ ] Master/Primary Filename not displaying in metadata records for single file concerts from CMF collection[#411](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/411)

These bugs maybe resolved as part of the implementation of a interim/tier one display strategy.

### Related Work

**Tickets for tier two display:**
- Apply tier two child work page (Desktop)[#396](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/396)
- Apply tier two child works page (Mobile)[#397](https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/397)
