### ISSUE TITLE
Collection clean-up

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#427]
### Descriptive Summary

Over time the DAMS team, library staff, and other endusers have identified issues with a number of the collections that are currently up in the DAMS.  The majority of these issues are metadata-related -- only one is file-related -- and can be resolved via export and roundtripping.

**Scope:**  This epic includes all non-MS 20 clean-up projects

### Acceptance Criteria

Done means:

- [ ]  MS 427: Corrupt characters, Sund__z! Weekly Newspaper #379
- [ ]  UA 50: 130+ Mis-titled Images #402 
- [ ]  UA 50: Description fields that contained escaped out semi-colons broken on to new lines #409 
- [ ]  MS 288: Update rightsHolder value for images in the Steve Rees collection #371 
- [ ]  Reparative Description Project: Changes to DAMS metadata #364 
- [ ]  Grateful Dead Media Collection #380 
- [ ]  Replace ms0020_neg_rmb-6702_09.tif with new image file #407
