### ISSUE TITLE
MVP needs assessment

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#542]
### Acceptance Criteria

**Front-end MVP**

- [x] Conduct MVP needs assessment: define tasks #423
- [x] Literature Review for MVP #493
- [x] Conduct MVP Stakeholder Interviews #491
- [x] Develop MVP Criteria #494
- [x] Finalize MVP Criteria for UI/UX #522

**Admin functionality MVP**

- [x] MVP assessment for admin user functionality #528

**Back-end support MVP**

- [x] MVP assessment for content support #520
- [ ] MVP: Prepare DAMS disaster recovery/business continuance plan #453
- [ ]  MVP: DAMS Re-architecture #585

**Comment by rmjaffe** [comment]
@chesleyperry Could you pull a copy of your content support reqs into the MVP folder in the DAMS team drive?  Thanks!
